sudo: required
services:
  - docker

before_install:
  - docker build -t tamkeithncube/docker-react -f Dockerfile.dev Dockerfile.dev Dockerfile.dev .

script:
  - docker run tamkeithncube/docker-react npm run test -- --coverage